development:
  server: "http://0.0.0.0:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://pi:9292/faye"
  secret_token: "34563465364fasdfasdf_my_sersecret"
