common: &common
    aws_s3_access_key: 'YOUR KEY HERE'
    aws_s3_secret_key: 'YOUR KEY HERE'

production:
    <<: *common
    aws_s3_bucket: 'YOUR BUCKET HERE' ##### to be changed
    aws_s3_db_bucket: 'YOUR DB BUCKET HERE' ##### to be changed
    gpg_email_address: 'YOUR EMAIL HERE'



