development:
  port: 9312
  enable_star: true
  morphology: libstemmer_de
  charset_type: 'utf-8' #https://www.stefanwille.com/2012/04/sphinx-search-thinking_sphinx-with-german-umlauts/
  charset_table: "0..9, A..Z->a..z, a..z, U+C4->U+E4, U+D6->U+F6, U+DC->U+FC, U+E4, U+F6, U+FC, U+DF"
  binlog_path:   /home/development/Projects/DocBox/tmp_sphinx_index
production:
  port: 9312
  bin_path: /usr/bin
  searchd_file_path: /data/DBServer/sphinx_index
  address: localhost 
  enable_star: true
  morphology: libstemmer_de
  charset_type: 'utf-8' #https://www.stefanwille.com/2012/04/sphinx-search-thinking_sphinx-with-german-umlauts/
  charset_table: "0..9, A..Z->a..z, a..z, U+C4->U+E4, U+D6->U+F6, U+DC->U+FC, U+E4, U+F6, U+FC, U+DF"
  pid_file: //tmp/sphinx.pid






